import { globby } from "globby";
import orderBy from "lodash.orderby";

const models = [
  "lmale",
  "mmale",
  "hmale",
  "lfemale",
  "mfemale",
  "hfemale",
  "lbioderm",
  "mbioderm",
  "hbioderm",
];

const weaponModels = [
  "chaingun",
  "disc",
  "elf",
  "energy",
  "grenade_launcher",
  "missile",
  "mortar",
  "plasmathrower",
  "repair",
  "shocklance",
  "sniper",
  "targeting",
];

export async function getSkinConfig() {
  const [defaultSkins, customSkins, customWeaponSkins] = await Promise.all([
    Promise.all(
      models.map((name) => globby(`./public/textures/*.${name}.png`))
    ),
    Promise.all(
      models.map((name) => globby(`../t2-skins/docs/skins/*.${name}.png`))
    ),
    Promise.all(
      weaponModels.map((name) =>
        globby(`../t2-skins/docs/skins/*/weapon_${name}.png`)
      )
    ),
  ]);

  return {
    defaultSkins: models.reduce((skins, name, i) => {
      skins[name] = orderBy(
        defaultSkins[i].map((name) =>
          name.replace(/(^.*\/|\.[lmh](male|female|bioderm)\.png$)/g, "")
        ),
        [(name) => name.toLowerCase()],
        ["asc"]
      );
      return skins;
    }, {}),
    customSkins: {
      ...models.reduce((skins, name, i) => {
        skins[name] = orderBy(
          customSkins[i].map((name) =>
            name.replace(/(^.*\/|\.[lmh](male|female|bioderm)\.png$)/g, "")
          ),
          [(name) => name.toLowerCase()],
          ["asc"]
        );
        return skins;
      }, {}),
      ...weaponModels.reduce((skins, name, i) => {
        skins[name] = orderBy(
          customWeaponSkins[i].map((name) => {
            const match = name.match(/\/([^/]+)\/weapon_\w+\.png$/);
            return match[1];
          }),
          [(name) => name.toLowerCase()],
          ["asc"]
        );
        return skins;
      }, {}),
    },
    modelDefaults: {
      // Players
      lmale: "Blood Eagle",
      mmale: "Blood Eagle",
      hmale: "Blood Eagle",
      lfemale: "Blood Eagle",
      mfemale: "Blood Eagle",
      hfemale: "Blood Eagle",
      lbioderm: "Storm",
      mbioderm: "Storm",
      hbioderm: "Storm",
      // Weapons
      chaingun: "weapon_chaingun",
      disc: "weapon_disc",
      elf: "weapon_elf",
      energy: "weapon_energy",
      grenade_launcher: "weapon_grenade_launcher",
      missile: "weapon_missile",
      mortar: "weapon_mortar",
      plasmathrower: "weapon_plasmathrower",
      repair: "weapon_repair",
      shocklance: "weapon_shocklance",
      sniper: "weapon_sniper",
      targeting: "weapon_targeting",
    },
    animationLabels: {
      Forward: "Run Forward",
      Back: "Run Backward",
      Back0: "Run Backward",
      Root: "Idle",
      Root2: "Run Backward",
      Root3: "Idle",
      Idlepda: "Idle (PDA)",
      PDA: "Idle (PDA)",
      Root1: "Idle (PDA)",
      Jump: "Jump",
      Jump0: "Jump (Alternate)",
      Jump1: "Jump (Alternate)",
      Jump2: "Jump (Alternate)",
      Jump3: "Jump (Alternate)",
      Jet: "Jet",
      Fall: "Fall",
      Land: "Land",
      Land1: "Land (Alternate)",
      ski: "Ski",
      Side: "Strafe Left",
      Celwave: "Wave",
      Celbow: "Bow",
      Celdisco: "Dance",
      Celdance: "Dance",
      Celflex: "Flex",
      Celflex1: "Flex",
      Celrocky: "Awesome",
      Celjump: "Awesome",
      Celsalute: "Salute",
      celTaunt: "Too Bad",
      CelebrationGora: "Wave Arms",
      Celgora: "Wave Arms",
      CelebrationJump: "Bull Charge",
      Tauntbull: "Bull Charge",
      CelebrationJump0: "Celebrate",
      CelebrationJump4: "The Greatest",
      CelebrationRoar: "Roar",
      Celroar: "Roar",
      Celraor: "Roar",
      Celflex2: "Flex",
      celyeah: "Yeah",
      celtaunt: "Too Bad",
      Tauntbutt: "Butt",
      Tauntkiss: "Blow Kiss",
      Tauntbest: "The Greatest",
      Taunimp: "Move!",
      Tauntimp: "Move!",
      Sitting: "Sit",
      Scoutroot: "Gravcycle",
      Recoilde: "Recoil",
      Light_recoil: "Recoil",
      Dieforward: "Death (Fall Forward)",
      DeathForward: "Death (Fall Forward)",
      Dieslump: "Death (Slump)",
      DeathSlump: "Death (Slump)",
      Diespin: "Death (Spin)",
      DeathSpin: "Death (Spin)",
      diechest: "Death (Hold Chest)",
      Diechest: "Death (Hold Chest)",
      DeathChest: "Death (Hold Chest)",
      Dieback: "Death (Hold Back)",
      DeathBack: "Death (Hold Back)",
      Diehead: "Death (Hold Head)",
      DeathHead: "Death (Hold Head)",
      Dieknees: "Death (On Knees)",
      DeathKnees: "Death (On Knees)",
      Dieleglf: "Death (Left Leg Injury)",
      Dieleglft: "Death (Left Leg Injury)",
      DeathLegLeft: "Death (Left Leg Injury)",
      Dielegrt: "Death (Right Leg Injury)",
      Dielegtrt: "Death (Right Leg Injury)",
      DeathLegRight: "Death (Right Leg Injury)",
      Dielegrt0: "Death (Right Leg Injury)",
      Diesidelf: "Death (Left Side)",
      DeathSideLeft: "Death (Left Side)",
      Diesidert: "Death (Right Side)",
      DeathSideRight: "Death (Right Side)",
      Diesidert0: "Death (Right Side Alternate)",
    },
    cameraOverrides: {
      chaingun: { target: "0m 0m 0m", fov: "12deg" },
    },
    animationLabelOverrides: {
      mmale: {
        Back: "Strafe Left",
      },
      mfemale: {
        Dielegrt: "Death (Slump)",
      },
      lbioderm: {
        Root: "Gravcycle",
      },
    },
    materials: {
      lmale: [{ name: "base", label: "Warrior" }],
      mmale: [{ name: "base", label: "Warrior" }],
      hmale: [{ name: "base", label: "Warrior" }],
      lfemale: [{ name: "base", label: "Warrior" }],
      mfemale: [{ name: "base", label: "Warrior" }],
      lbioderm: [{ name: "base", label: "Warrior" }],
      mbioderm: [{ name: "base", label: "Warrior" }],
      hbioderm: [{ name: "base", label: "Warrior" }],
      disc: [
        { name: "weapon_disc", label: "Weapon" },
        {
          name: "dcase00",
          label: "Disc Case",
          size: [256, 256],
          baseColorFactor: [1, 1, 1, 0.7],
          emissiveFactor: [1, 1, 1],
          emissiveTexture: true,
          alphaMode: "BLEND",
          metallicFactor: 0,
          roughnessFactor: 1,
        },
      ],
      chaingun: [{ label: "Chaingun", name: "weapon_chaingun" }],
      grenade_launcher: [
        { label: "Grenade Launcher", name: "weapon_grenade_launcher" },
      ],
      sniper: [
        { label: "Weapon", name: "weapon_sniper" },
        { label: "Green Light", name: "greenlight", hasDefault: false },
        { label: "Red Light", name: "lite_red", hasDefault: false },
      ],
      plasmathrower: [{ label: "Weapon", name: "weapon_plasmathrower" }],
      energy: [
        {
          label: "Weapon",
          name: "blinn1",
          file: "weapon_energy",
        },
      ],
      shocklance: [
        { label: "Weapon", name: "weapon_shocklance", size: [512, 256] },
        {
          label: "Glow",
          name: "weapon_shocklance_glow_",
          file: "weapon_shocklance_glow ",
          emissiveFactor: [1, 1, 1],
          alphaMode: "MASK",
          alphaCutoff: 255,
          emissiveTexture: true,
          metallicFactor: 0,
          roughnessFactor: 1,
          size: [256, 128],
        },
      ],
      elf: [
        { index: 0, label: "Weapon", name: "weapon_elf" },
        { index: 1, label: "Glow", name: "weapon_elf0", file: "weapon_elf" },
      ],
      missile: [{ label: "Weapon", name: "weapon_missile" }],
      mortar: [{ label: "Weapon", name: "weapon_mortar" }],
      repair: [{ label: "Weapon", name: "weapon_repair" }],
      targeting: [{ label: "Weapon", name: "weapon_targeting" }],
    },
    animations: {
      global: [
        "Forward",
        "Back",
        // "Head",
        "Jump",
        "Jet",
        "Fall",
        "Land",
        "ski",
        // "Lookde",
        // "Looknw",
        "Root",
      ],
      lmale: [
        "Idlepda",
        "Side",
        "Jump0",
        "Land1",
        "Recoilde",
        "Celwave",
        "Celdisco",
        "Celflex",
        "Celrocky",
        "Celsalute",
        "celTaunt",
        "Taunimp",
        "Tauntbest",
        "Dieback",
        "diechest",
        "Dieforward",
        "Diehead",
        "Dieknees",
        "Dieleglf",
        "Dielegrt",
        "Diesidelf",
        "Diesidert",
        "Dieslump",
        "Diespin",
        // "Headside",
        // "Lookms",
        // "Looksn",
        "Scoutroot",
        "Sitting",
      ],
      mmale: [
        "Back0",
        "Jump3",
        "Recoilde",
        "Celwave",
        "Celdance",
        "Celflex",
        "Celrocky",
        "Celsalute",
        "celtaunt",
        "Tauntbest",
        "Tauntimp",
        "Dieback",
        "Diechest",
        "Dieforward",
        "Diehead",
        "Dieknees",
        "Dieleglf",
        "Dielegrt",
        "Diesidelf",
        "Diesidert",
        "Diespin",
        // "Head1",
        // "Lookms",
        // "Looksn",
        // "Root2",
        "Sitting",
      ],
      hmale: [
        "Idlepda",
        "Jump1",
        "Side",
        "Recoilde",
        "Celwave",
        "Celdance",
        "Celflex",
        "Celjump",
        "Celsalute",
        "celtaunt",
        "Tauntbest",
        "Tauntimp",
        "Dieback",
        "Diechest",
        "Dieforward",
        "Diehead",
        "Dieknees",
        "Dielegrt",
        "Diesidelf",
        "Diesidert",
        "Diesidert0",
        "Dieslump",
        "Diespin",
        // "Headside",
        // "Lookms",
      ],
      lfemale: [
        "Idlepda",
        "Jump1",
        "Side",
        "Recoilde",
        "Celwave",
        "Celbow",
        "Celdance",
        "Celsalute",
        "Tauntbest",
        "Tauntbutt",
        "Tauntimp",
        "Tauntkiss",
        "Dieback",
        "Diechest",
        "Dieforward",
        "Diehead",
        "Dieknees",
        "Dieleglf",
        "Dielegrt",
        "Diesidelf",
        "Diesidert",
        "Dieslump",
        "Diespin",
        // "Head0",
        // "Lookms",
        // "Looksn",
        "Scoutroot",
        "Sitting",
      ],
      mfemale: [
        "Idlepda",
        "Jump1",
        "Side",
        "Recoilde",
        "Celwave",
        "Celbow",
        "Celdisco",
        "Celsalute",
        "Tauntbest",
        "Tauntbutt",
        "Tauntimp",
        "Tauntkiss",
        "Dieback",
        "Diechest",
        "Dieforward",
        "Diehead",
        "Dieknees",
        "Dieleglf",
        "Dielegrt",
        "Dielegrt0",
        "Diesidelf",
        "Diesidert",
        "Diespin",
        // "Headside",
        // "Looksn",
        // "Lookth",
        "Sitting",
      ],
      lbioderm: [
        "Root3",
        "PDA",
        "Jump2",
        "Side",
        "Light_recoil",
        "CelebrationGora",
        "CelebrationJump",
        "CelebrationJump0",
        "CelebrationJump4",
        "CelebrationRoar",
        "Salute",
        "Celflex2",
        "celyeah",
        "DeathBack",
        "DeathChest",
        "DeathForward",
        "DeathHead",
        "DeathKnees",
        "DeathLegLeft",
        "DeathLegRight",
        "DeathSideLeft",
        "DeathSideRight",
        "DeathSlump",
        "DeathSpin",
        // "Head1",
        // "Lookms",
        "Sitting",
      ],
      mbioderm: [
        "Root1",
        "Jump2",
        "Side",
        "Recoilde",
        "Salute",
        "Celflex1",
        "Celgora",
        "Celjump",
        "Celroar",
        "celyeah",
        "Tauntbest",
        "Tauntbull",
        "DeathBack",
        "DeathChest",
        "DeathHead",
        "DeathSideLeft",
        "DeathSpin",
        "Dieforward",
        "Dieknees",
        "Dieleglft",
        "Dielegtrt",
        "Diesidert",
        "Dieslump",
        // "Head0",
        // "Lookms",
        "Sitting",
      ],
      hbioderm: [
        "Root1",
        "Jump2",
        "Side",
        "Recoilde",
        "Salute",
        "Celflex2",
        "Celgora",
        "Celjump",
        "Celraor",
        "celyeah",
        "Tauntbest",
        "Tauntbull",
        "DeathBack",
        "DeathChest",
        "DeathForward",
        "DeathHead",
        "DeathKnees",
        "DeathLegLeft",
        "DeathLegRight",
        "DeathSideLeft",
        "DeathSideRight",
        "DeathSlump",
        "DeathSpin",
        // "Head0",
        // "Lookms",
      ],
    },
  };
}
